name: Build full application and push to docker hub stable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: ['3.6.3']

    steps:
    - uses: actions/checkout@v4
    - uses: s4u/setup-maven-action@v1.19.0
      with:
        java-version: 21
        maven-version: ${{ matrix.maven }}
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    
    - name: Starting postgres for backend build
      run: cd test-db && docker compose up -d
      
    - name: Running maven build
      run: cd backend && mvn clean package
      
    - name: Stopping postgres
      run: cd test-db && docker compose down
      
    - name: Building frontend
      run: cd frontend && npm i && npm run build
      
    - name: Build docker image for backend
      run: cd backend && docker build . -t "prinshertog/kokenmetlisa-backend:v2-stable" && docker push prinshertog/kokenmetlisa-backend:v1-stable
      
    - name: Build docker image for frontend
      run: cd frontend && docker build . -t "prinshertog/kokenmetlisa-frontend:v2-stable" && docker push prinshertog/kokenmetlisa-frontend:v1-stable
